import uvm_pkg::*;
`include "uvm_macros.svh"
`include "package_params.sv"

//`include "fifo.v"
`include "interface.sv"
`include "seq_item.sv"
`include "sequence.sv"
`include "write_sequence.sv"
`include "read_sequence.sv"
`include "write_read_sequence.sv"

`include "sequencer.sv"
`include "driver.sv"
`include "monitor.sv"
`include "agent.sv"
`include "scoreboard.sv"
`include "env.sv"
`include "base_test.sv"
`include "write_test.sv"
`include "read_test.sv"
`include "all_test.sv"

`include "write_read_test.sv"
`include "top.sv"
